[MM_DEBUG][audio] _shape_infer leader args=<class 'tuple'> len=0 kw=['audio_inputs']
[MM_DEBUG][audio] forward returned None. kwargs summary: {'audio_inputs': 'NoneType'}
[rank0]: Traceback (most recent call last):
[rank0]:   File "/local/desk/qwen2.5_omni_3b_devide_head.py", line 968, in <module>
[rank0]:     main()
[rank0]:   File "/local/desk/qwen2.5_omni_3b_devide_head.py", line 794, in main
[rank0]:     sched.step(audio_inputs=aud_pack, attention_mask=attn, target=tgt)
[rank0]:   File "/local/desk/pipelining_source_code/schedules.py", line 1366, in step
[rank0]:     self._step_microbatches(args_split, kwargs_split, targets_split, losses)
[rank0]:   File "/local/desk/schedule_runtime.py", line 926, in _step_microbatches
[rank0]:     self._initialize_stages(arg_mbs[0], kwarg_mbs[0])
[rank0]:   File "/local/desk/pipelining_source_code/schedules.py", line 1289, in _initialize_stages
[rank0]:     next_stage_args = stage._prepare_forward_infra(
[rank0]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/local/desk/pipelining_source_code/stage.py", line 1463, in _prepare_forward_infra
[rank0]:     outputs = self._shape_inference(args, kwargs)
[rank0]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/local/desk/stage_with_mutiple_ranks.py", line 1254, in _shape_inference
[rank0]:     raise RuntimeError(f"[{mt}] _shape_inference: submodule returned None; please verify inputs and encoders")
[rank0]: RuntimeError: [audio] _shape_inference: submodule returned None; please verify inputs and encoders


其他的rank都因为上面rank出错而被挂掉